### PR TITLE
Misc changes and feature additions

### PR DESCRIPTION
**Pull request by nims11**
* Deploy Script
* Editorial System
* HTML editor
* XSS resolved

### CODE REVIEW

**Comment by nims11** [comment]
Loads of changes, please merge. Also, can the aurora repo in the ACM group be made the main one instead? I am thinking of doing a code cleanup and review followed by encouraging people to start contributing to it.

**Comment by pushkar8723** [comment]
I will review again, merge and do clean up (if required).

And I also feel that development of Aurora has been very slow now. There are some areas which needs to be improved, new features can be added and many design changes are required. I was planning to start working on it but since I don't get much free time, progress will be slow. 

So, I suggest you to just reach out to junior batches and see if people are interested in contributing to Aurora. If you find good participation I will share my plan with them and transfer ownership of this repo to ACM. This will be beneficial for both Aurora and the students. May be we can start sometime in March?

Ping me when you are free and we will discuss it.

**Comment by nims11** [comment]
Sure. Actually we are short on numbers with me handling ACM, aurora and
dchub all at the same time. I am currently working on a judge.py
replacement which is a more secure and better scalable. I am preparing to
pass on dchub to juniors after midsem. For aurora, we have planned on
promoting an open source drive to call for contributions. But before that i
m doing a code and security review of the php codes.

On Tuesday, February 17, 2015, Pushkar Anand <notifications@github.com>
wrote:
> I will review again, merge and do clean up (if required).
>
> And I also feel that development of Aurora has been very slow now. There
are some areas which needs to be improved, new features can be added and
many design changes are required. I was planning to start working on it but
since I don't get much free time, progress will be slow.
>
> So, I suggest you to just reach out to junior batches and see if people
are interested in contributing to Aurora. If you find good participation I
will share my plan with them and transfer ownership of this repo to ACM.
This will be beneficial for both Aurora and the students. May be we can
start sometime in March?
>
> Ping me when you are free and we will discuss it.
>
> --
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/TvUAeqFe9T5dCwE6D6RvaE0kPAmPLSLwEKq1s_pdv-GPCRbXKFORK30eLduFiHoHx727Y_i_guWioJ5yDBzok7OeUxrwf29eN6RNGd4cuF64FkSludEu1SVXrgYjrpOSMJrDTkhlu9K0E_dN7nWsiTB9Ytx3tA=s0-d-e1-ft#https://github.com/notifications/beacon/ABOJ9751r6zhQcmh8guYG1rrVcPUL4PHks5ns0R2gaJpZM4CxEUf.gif
>

-- 
Regards,
Nimesh Ghelani

**Comment by pushkar8723** [comment]
I merged the code and did a little bit of clean up.
It needs few inputs from your side.

Create a Readme.md for Scripts folder.
Readme should be able to tell people
1. What it is used for?
2. How it can be used (install/start)?

**Pull request merged**
